### ISSUE TITLE
How to Set environment variable CMAKE_MODULES?

### ISSUE THREAD

**Issue by freeNastran** [SAP/fedem-gui#27]
Hi,

I am trying to build the gui under win 10 with vs 2022 and got the error when run cmake:

`-- Generating build project for D:/FEDEM/fedem-gui-main
-- ERROR : Missing path to FedemConfig.cmake
CMake Error at CMakeLists.txt:45 (message):
  Set environment variable CMAKE_MODULES and try again`

I can't find file FedemConfig.cmake.
how to set this and to what value?

Cheers

John

**Comment by kmoks** [comment]
The `FedemConfig.cmake` file resides in a sub-module. You will not get it unless you use the --recurse-submodules option when cloning this repository, i.e.:

    git clone --recurse-submodules git@github.com:SAP/fedem-gui.git

This is explained in the [BUILD.md](https://github.com/SAP/fedem-gui/blob/main/BUILD.md#build-the-fedem-gui-application) file.

**Comment by freeNastran** [comment]
Thanks. Only downloaded as zip. Don't know --recurse-submodules before.

But got this error:
`D:\Fedem-src>git clone --recurse-submodules git@github.com:SAP/fedem-gui.git
Cloning into 'fedem-gui'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.`

And change to this works. 

`git clone --recurse-submodules https://github.com/SAP/fedem-gui.git`

I found FedemConfig.cmake in the Foundation module.

**Comment by kmoks** [comment]
yes, you probably need to upload your public SSH key to your github profile before you can use the ssh-access method. But https also works like you said.

The zip-files that are  generated by github will not contain the sub-module contents. Then you manually have to repeat that process for each sub-module referenced, and then unzip in the right place locally. Then recursive clone is much easier.
